[env]
TERM = "xterm-256color"

[font]
size = 12.0

[general]
import = [
#    "~/.config/alacritty/themes/themes/dracula_plus.toml"
    "~/.config/alacritty/themes/themes/gnome_terminal.toml"
#    "~/.config/alacritty/themes/themes/citylights.toml"
#    "~/.config/alacritty/themes/themes/enfocado_dark.toml"
#    "~/.config/alacritty/themes/themes/base16_default_dark.toml"
#    "~/.config/alacritty/themes/themes/horizon_dark.toml"
]

[window]
padding = { x = 4, y = 4 }
decorations = "None"
opacity = 0.9

