# Monitors layout

$monleft=DP-2
$moncenter=DP-1
$monright=HDMI-A-1

monitor=$moncenter,highres,0x0,1
monitor=$monleft,highres,auto-left,1
monitor=$monright,highres,auto-right,1
#monitor=$monleft,disable
#monitor=$monright,disable

